## This module contains two functions: makeCacheMatrix and cacheSolve. These
## functions work together to create a "special" matrix that is capable of 
## having its inverse cached. In some situations, this caching can improve the
## performance if the inverse is repeatedly calculated.

## makeCacheMatrix takes a "normal" R matrix and returns a "special" R matrix
## that is able to cache the inverse of the matrix. A "special" matrix is 
## represented by a list that has four components:
## set to matrix
## get to get the matrix
## setInverse to set the inverse of the matrix
## getInverse to get the inverse of the matrix

makeCacheMatrix <- function(x = matrix()) {
    m <- NULL
    set <- function(y) {
      x <<- y
      m <<- NULL
    }
    get <- function() x
    setInverse <- function(inverse) m <<- inverse
    getInverse <- function() m
    list(set = set, get = get,
         setInverse = setInverse,
         getInverse = getInverse)
}

## cacheSolve takes a "special" R matrix (generated by makeCacheMatrix) and 
## returns the inverse of the matrix. If the inverse has already been calculated
## cacheSolve will return the cached value.

cacheSolve <- function(x, ...) {
    m <- x$getInverse()
    if(!is.null(m)) {
      message("getting cached data")
      return(m)
    }
    data <- x$get()
    m <- solve(data, ...)
    x$setInverse(m)
    m
}
